version: '3.2'

services:
  app:
    build: ./docker/rails
    container_name: rails_application
    volumes:
     - './:/app'
     - 'bundle:/bundle'
    ports:
     - '3000:3000'
    links:
      - db
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://db:3306
  db:
    image: mysql:5.7
    container_name: mysql_database
    ports:
      - "3306:3306"
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
volumes:
  mysql:
    driver: local
  bundle:
    driver: local
